name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install
        working-directory: ./backend

      - name: Start the server (if applicable)
        run: npm start &
        working-directory: ./backend
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_TYPE: ${{ secrets.DB_TYPE }}
          PORT: ${{ secrets.PORT }}

      - name: Wait for server to be ready
        run: sleep 10
          
      - name: Google auth
        id: auth
        uses: google-github-actions/auth@v1
        with: 
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          tags: shop-project-valeriia:${{ github.sha }}
          platforms: linux/amd64
          context: backend/.
          push: false

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@main
        with:
          service: shop-project-valeriia
          image: gcr.io/${{ secrets.PROJECT_ID }}/shop-project-valeriia:${{ github.sha }}
          region: europe-west1
          platform: managed
          allow-unauthenticated: true